variables:
  DOKCER_IMAGE_URL: registry.gitlab.com/jh-school/mealapp/admin-front
  SERVICE_NAME: mealapp-admin-front


stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: docker:latest
  stage: build
  tags:
    - gitlab-org-docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $DOKCER_IMAGE_URL .
    - docker push $DOKCER_IMAGE_URL
  only:
    - main

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker stop $SERVICE_NAME && docker rm $SERVICE_NAME && docker rmi $DOKCER_IMAGE_URL
    - docker run -d -p 3000:3000 --restart unless-stopped --name $SERVICE_NAME $DOKCER_IMAGE_URL
  tags:
    - jhapp-server
  only:
    - main